#!/usr/bin/env python

# -*- coding:utf-8 -*-

from __future__ import unicode_literals

import os
import sys
import shutil
import zipfile

from util.config import Config
from util.fonts import Fonts
from util import error

def main():
    Config.read_args()
    fonts = Fonts()
    fonts.handle_fonts()

    sys.exit(0)

# ####################################
# Finally launch the program
if __name__ == "__main__":
    main()
